"""empty message

Revision ID: 54e89720dbc0
Revises: 
Create Date: 2023-04-26 05:15:20.390536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e89720dbc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('initial_order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_integration_id', sa.String(length=50), nullable=False),
    sa.Column('resource_integration_id', sa.String(length=50), nullable=False),
    sa.Column('trading_point_integration_id', sa.String(length=50), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('order_amount', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('address_integration_id', sa.String(length=50), nullable=True),
    sa.Column('delivery_address', sa.String(length=500), nullable=True),
    sa.Column('delivery_type_integration_id', sa.String(length=50), nullable=False),
    sa.Column('payment_type_integration_id', sa.String(length=50), nullable=False),
    sa.Column('filial_integration_id', sa.String(length=50), nullable=False),
    sa.Column('consultant_integration_id', sa.String(length=50), nullable=True),
    sa.Column('total_loyalty_points_charged', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'order_integration_id', 'resource_integration_id'),
    sa.UniqueConstraint('order_integration_id')
    )
    op.create_table('new_policy_level',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('new_policy_integration_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'new_policy_integration_id'),
    sa.UniqueConstraint('new_policy_integration_id')
    )
    op.create_table('sales_channel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sales_channel_integration_id', sa.String(length=50), nullable=False),
    sa.Column('is_able_to_sell', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'sales_channel_integration_id'),
    sa.UniqueConstraint('sales_channel_integration_id')
    )
    op.create_table('valta_product',
    sa.Column('product_integration_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('vendor_code', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.String(length=255), nullable=False),
    sa.Column('present_for_vet', sa.Boolean(), nullable=False),
    sa.Column('valid_for_loyalty', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('product_integration_id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('vendor_code')
    )
    op.create_table('wallet',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vc_balance', sa.Integer(), nullable=False),
    sa.Column('vc_service_balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('vc_balance >= 0', name='check_vc_balance_positive'),
    sa.CheckConstraint('vc_service_balance >= 0', name='check_vc_service_balance_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('initial_order_product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_integration_id', sa.String(length=50), nullable=False),
    sa.Column('product_integration_id', sa.String(length=50), nullable=True),
    sa.Column('vendor_code', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('user_price', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('automatic_discount', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('loyalty_points_charged', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('is_valta_product', sa.Boolean(), nullable=False),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.Column('filtered_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_integration_id'], ['initial_order.order_integration_id'], ),
    sa.ForeignKeyConstraint(['product_integration_id'], ['valta_product.product_integration_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loyalty_product_rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loyalty_product_rule_id', sa.String(length=50), nullable=False),
    sa.Column('product_integration_id', sa.String(length=50), nullable=False),
    sa.Column('sales_channel_integration_id', sa.String(length=50), nullable=True),
    sa.Column('new_policy_integration_id', sa.String(length=50), nullable=True),
    sa.Column('cashback_percent', sa.Integer(), nullable=False),
    sa.Column('times_normal', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['new_policy_integration_id'], ['new_policy_level.new_policy_integration_id'], ),
    sa.ForeignKeyConstraint(['product_integration_id'], ['valta_product.product_integration_id'], ),
    sa.ForeignKeyConstraint(['sales_channel_integration_id'], ['sales_channel.sales_channel_integration_id'], ),
    sa.PrimaryKeyConstraint('id', 'loyalty_product_rule_id'),
    sa.UniqueConstraint('loyalty_product_rule_id')
    )
    op.create_table('user',
    sa.Column('user_integration_id', sa.String(length=50), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('second_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('sales_channel_integration_id', sa.String(length=50), nullable=False),
    sa.Column('new_policy_integration_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['new_policy_integration_id'], ['new_policy_level.new_policy_integration_id'], ),
    sa.ForeignKeyConstraint(['sales_channel_integration_id'], ['sales_channel.sales_channel_integration_id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('user_integration_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('wallet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('loyalty_product_rule')
    op.drop_table('initial_order_product')
    op.drop_table('wallet')
    op.drop_table('valta_product')
    op.drop_table('sales_channel')
    op.drop_table('new_policy_level')
    op.drop_table('initial_order')
    # ### end Alembic commands ###
